#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_etcd_proxy="0.0.1"
  jq -n --arg etcd_proxy "$ver_etcd_proxy" '{etcd_proxy: $etcd_proxy}'
}

version "$@"
